openapi: 3.2.0
info:
  title: JustCall AI API
  description: 'REST APIs

    The REST APIs provide programmatic access to read and write JustCall data. Create a new contact, read them, add notes, and more'
  version: '2'
  contact: {}
servers:
- url: https://api.justcall.io
tags:
- name: JustCall AI
paths:
  /v2/calls_ai:
    get:
      operationId: call_ai_list
      summary: List calls AI data
      description: Utilize this endpoint to access AI generated analysis for JustCall and Sales Dialer calls.
      parameters:
      - name: platform
        required: false
        in: query
        description: Select the platform to retrieve associated call details.
        schema:
          default: justcall
          enum:
          - justcall
          - sales_dialer
          type: string
      - description: Set fetch_transcription to true to fetch the transcription generated by JustCall AI for your call. Default entry is false.
        required: false
        name: fetch_transcription
        in: query
        schema:
          default: false
          type: boolean
      - description: Set fetch_summary to true to fetch the summary generated by JustCall AI for your call. Default entry is true.
        required: false
        name: fetch_summary
        in: query
        schema:
          default: true
          type: boolean
      - description: Set fetch_ai_insights to true to fetch the coaching insights generated by JustCall AI for your call. Default entry is true.
        required: false
        name: fetch_ai_insights
        in: query
        schema:
          default: true
          type: boolean
      - name: agent_id
        required: false
        in: query
        description: ID of the agent for whom the AI data for calls are to be fetched. Agent ID can be accessed using <a href="https://justcall.io/developer-docs/#list_users">List all users API</a>.
        schema:
          type: number
      - name: from_datetime
        required: false
        in: query
        description: Datetime in <b>yyyy-mm-dd hh:mm:ss</b> or <b>yyyy-mm-dd</b> format starting from when the calls AI data are to be fetched in <b>UTC Timezone</b>.
        schema:
          type: string
      - name: to_datetime
        required: false
        in: query
        description: Datetime in <b>yyyy-mm-dd hh:mm:ss</b> or <b>yyyy-mm-dd</b> format till when the calls AI data are to be fetched in <b>UTC Timezone</b>.
        schema:
          type: string
      - name: page
        required: false
        in: query
        description: Page number for which calls are to be fetched.
        schema:
          type: number
      - name: per_page
        required: false
        in: query
        description: Number count of calls to be fetched per page.<br>Default value is 10 and maximum value is 20.
        schema:
          type: number
      - name: order
        required: false
        in: query
        description: 'Order in which the calls should appear based on ‘Date created’ASC : Older data will appear first followed by recent oneDESC: Recent data will appear first followed by older one'
        schema:
          default: desc
          enum:
          - asc
          - desc
          - natural
          type: string
      responses:
        '200':
          description: Successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CallAiResponseDTOV2'
        '400':
          description: Failed due to bad request params.
        '401':
          description: Failed due to unauthorized access.
        '403':
          description: This error occurred when there is some validation error or you don't have access to that resource.
        '404':
          description: Requested resource may not exist.
        '500':
          description: This is due to internal server error reason, in this case please contact our support team with attached uuid.
      tags:
      - JustCall AI
      security:
      - AccessToken: []
  /v2.1/calls_ai:
    get:
      operationId: call_ai_list_v21
      summary: List calls AI data
      description: Utilize this endpoint to access AI generated analysis for JustCall and Sales Dialer calls.
      parameters:
      - name: platform
        required: false
        in: query
        description: Select the platform to retrieve associated call details.
        schema:
          default: justcall
          enum:
          - justcall
          - sales_dialer
          type: string
      - description: Set fetch_transcription to true to fetch the transcription generated by JustCall AI for your call. Default entry is false.
        required: false
        name: fetch_transcription
        in: query
        schema:
          default: false
          type: boolean
      - description: Set fetch_summary to true to fetch the summary generated by JustCall AI for your call. Default entry is true.
        required: false
        name: fetch_summary
        in: query
        schema:
          default: true
          type: boolean
      - description: Set fetch_ai_insights to true to fetch the coaching insights generated by JustCall AI for your call. Default entry is true.
        required: false
        name: fetch_ai_insights
        in: query
        schema:
          default: true
          type: boolean
      - name: agent_id
        required: false
        in: query
        description: ID of the agent for whom the AI data for calls are to be fetched. Agent ID can be accessed using <a href="https://justcall.io/developer-docs/#list_users">List all users API</a>.
        schema:
          type: number
      - name: from_datetime
        required: false
        in: query
        description: Datetime in <b>yyyy-mm-dd hh:mm:ss</b> or <b>yyyy-mm-dd</b> format starting from when the calls AI data are to be fetched in <b>user's timezone</b>.
        schema:
          type: string
      - name: to_datetime
        required: false
        in: query
        description: Datetime in <b>yyyy-mm-dd hh:mm:ss</b> or <b>yyyy-mm-dd</b> format till when the calls AI data are to be fetched in <b>user's timezone</b>.
        schema:
          type: string
      - name: page
        required: false
        in: query
        description: Page number for which calls are to be fetched.
        schema:
          type: number
      - name: per_page
        required: false
        in: query
        description: Number count of calls to be fetched per page.<br>Default value is 10 and maximum value is 20.
        schema:
          type: number
      - name: order
        required: false
        in: query
        description: 'Order in which the calls should appear based on ‘Date created’ASC : Older data will appear first followed by recent oneDESC: Recent data will appear first followed by older one'
        schema:
          default: desc
          enum:
          - asc
          - desc
          - natural
          type: string
      - description: Set fetch_action_items to true to fetch the action items generated by JustCall AI for your call. Default entry is true.
        required: false
        name: fetch_action_items
        in: query
        schema:
          default: true
          type: boolean
      - description: Set fetch_smart_chapters to true to fetch the smart chapters generated by JustCall AI for your call. Default entry is true.
        required: false
        name: fetch_smart_chapters
        in: query
        schema:
          default: true
          type: boolean
      - name: phone_number
        required: false
        in: query
        description: Phone or Calling number (JustCall or Sales Dialer) for which AI-generated call data will be fetched. The number must be linked with the selected platform. If no platform is specified, the default is <b>justcall</b>.
        schema:
          type: string
      - name: ai_agent_ids
        required: false
        in: query
        description: IDs of the AI agents for which the calls are to be fetched. AI Agent IDs can be accessed using <a href="https://developer.justcall.io/reference/list_voice_agents_v21"> List all AI agents API</a>.
        schema:
          type: array
          items:
            type: string
      responses:
        '200':
          description: Successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CallAiResponseDTOV21'
        '400':
          description: Failed due to bad request params.
        '401':
          description: Failed due to unauthorized access.
        '403':
          description: This error occurred when there is some validation error or you don't have access to that resource.
        '404':
          description: Requested resource may not exist.
        '500':
          description: This is due to internal server error reason, in this case please contact our support team with attached uuid.
      tags:
      - JustCall AI
      security:
      - AccessToken: []
  /v2/calls_ai/{id}:
    get:
      operationId: call_ai_get
      summary: Get AI data
      description: Retrieve AI generated analysis for a particular JustCall or a Sales Dialer call using this endpoint.
      parameters:
      - name: platform
        required: false
        in: query
        description: Select the platform to retrieve associated call details.
        schema:
          default: justcall
          enum:
          - justcall
          - sales_dialer
          type: string
      - description: Set fetch_transcription to true to fetch the transcription generated by JustCall AI for your call. Default entry is false.
        required: false
        name: fetch_transcription
        in: query
        schema:
          default: false
          type: boolean
      - description: Set fetch_summary to true to fetch the summary generated by JustCall AI for your call. Default entry is true.
        required: false
        name: fetch_summary
        in: query
        schema:
          default: true
          type: boolean
      - description: Set fetch_ai_insights to true to fetch the coaching insights generated by JustCall AI for your call. Default entry is true.
        required: false
        name: fetch_ai_insights
        in: query
        schema:
          default: true
          type: boolean
      - name: id
        required: true
        in: path
        description: Unique id of the call generated by JustCall
        schema:
          type: number
      responses:
        '200':
          description: Successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CallAiResponseDTOV2'
        '400':
          description: Failed due to bad request params.
        '401':
          description: Failed due to unauthorized access.
        '403':
          description: This error occurred when there is some validation error or you don't have access to that resource.
        '404':
          description: Requested resource may not exist.
        '500':
          description: This is due to internal server error reason, in this case please contact our support team with attached uuid.
      tags:
      - JustCall AI
      security:
      - AccessToken: []
  /v2.1/calls_ai/{id}:
    get:
      operationId: call_ai_get_v21
      summary: Get AI data
      description: Retrieve AI generated analysis for a particular JustCall or a Sales Dialer call using this endpoint.
      parameters:
      - name: platform
        required: false
        in: query
        description: Select the platform to retrieve associated call details.
        schema:
          default: justcall
          enum:
          - justcall
          - sales_dialer
          type: string
      - description: Set fetch_transcription to true to fetch the transcription generated by JustCall AI for your call. Default entry is false.
        required: false
        name: fetch_transcription
        in: query
        schema:
          default: false
          type: boolean
      - description: Set fetch_summary to true to fetch the summary generated by JustCall AI for your call. Default entry is true.
        required: false
        name: fetch_summary
        in: query
        schema:
          default: true
          type: boolean
      - description: Set fetch_ai_insights to true to fetch the coaching insights generated by JustCall AI for your call. Default entry is true.
        required: false
        name: fetch_ai_insights
        in: query
        schema:
          default: true
          type: boolean
      - description: Set fetch_action_items to true to fetch the action items generated by JustCall AI for your call. Default entry is true.
        required: false
        name: fetch_action_items
        in: query
        schema:
          default: true
          type: boolean
      - description: Set fetch_smart_chapters to true to fetch the smart chapters generated by JustCall AI for your call. Default entry is true.
        required: false
        name: fetch_smart_chapters
        in: query
        schema:
          default: true
          type: boolean
      - name: id
        required: true
        in: path
        description: Unique id of the call generated by JustCall
        schema:
          type: number
      responses:
        '200':
          description: Successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CallAiResponseDTOV21'
        '400':
          description: Failed due to bad request params.
        '401':
          description: Failed due to unauthorized access.
        '403':
          description: This error occurred when there is some validation error or you don't have access to that resource.
        '404':
          description: Requested resource may not exist.
        '500':
          description: This is due to internal server error reason, in this case please contact our support team with attached uuid.
      tags:
      - JustCall AI
      security:
      - AccessToken: []
  /v2/calls_ai/summary/{id}:
    get:
      operationId: call_ai_summary
      summary: Get call summary
      description: A summary of the key highlights and takeaways from a call.
      parameters:
      - name: id
        required: true
        in: path
        description: Unique id of the call generated by JustCall
        schema:
          type: number
      - name: platform
        required: false
        in: query
        description: Select the platform to retrieve associated call details.
        schema:
          default: justcall
          enum:
          - justcall
          - sales_dialer
          type: string
      responses:
        '200':
          description: Successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CallAISummaryResponseDTO'
        '400':
          description: Failed due to bad request params.
        '401':
          description: Failed due to unauthorized access.
        '403':
          description: This error occurred when there is some validation error or you don't have access to that resource.
        '404':
          description: Requested resource may not exist.
        '500':
          description: This is due to internal server error reason, in this case please contact our support team with attached uuid.
      tags:
      - JustCall AI
      security:
      - AccessToken: []
  /v2/calls_ai/moments/{id}:
    get:
      operationId: call_ai_moments
      summary: Get call moments
      description: A summary of the key highlights and takeaways from a call.
      parameters:
      - name: id
        required: true
        in: path
        description: Unique id of the call generated by JustCall
        schema:
          type: number
      - name: platform
        required: false
        in: query
        description: Select the platform to retrieve associated call details.
        schema:
          default: justcall
          enum:
          - justcall
          - sales_dialer
          type: string
      responses:
        '200':
          description: Successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CallAIMomentResponseDTO'
        '400':
          description: Failed due to bad request params.
        '401':
          description: Failed due to unauthorized access.
        '403':
          description: This error occurred when there is some validation error or you don't have access to that resource.
        '404':
          description: Requested resource may not exist.
        '500':
          description: This is due to internal server error reason, in this case please contact our support team with attached uuid.
      tags:
      - JustCall AI
      security:
      - AccessToken: []
  /v2/calls_ai/sentiments/{id}:
    get:
      operationId: call_ai_sentiments
      summary: Get call sentiment
      description: Overall analysis of the sentiment of the customer based on words and tone.
      parameters:
      - name: id
        required: true
        in: path
        description: Unique id of the call generated by JustCall
        schema:
          type: number
      - name: platform
        required: false
        in: query
        description: Select the platform to retrieve associated call details.
        schema:
          default: justcall
          enum:
          - justcall
          - sales_dialer
          type: string
      responses:
        '200':
          description: Successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CallAISentimentResponseDTO'
        '400':
          description: Failed due to bad request params.
        '401':
          description: Failed due to unauthorized access.
        '403':
          description: This error occurred when there is some validation error or you don't have access to that resource.
        '404':
          description: Requested resource may not exist.
        '500':
          description: This is due to internal server error reason, in this case please contact our support team with attached uuid.
      tags:
      - JustCall AI
      security:
      - AccessToken: []
  /v2/calls_ai/analytics/{id}:
    get:
      operationId: call_ai_analytics
      summary: Get call analytics
      description: Get comprehensive insights for a holistic understanding of call dynamics.
      parameters:
      - name: id
        required: true
        in: path
        description: Unique id of the call generated by JustCall
        schema:
          type: number
      - name: platform
        required: false
        in: query
        description: Select the platform to retrieve associated call details.
        schema:
          default: justcall
          enum:
          - justcall
          - sales_dialer
          type: string
      responses:
        '200':
          description: Successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CallAIAnalyticsResponseDTO'
        '400':
          description: Failed due to bad request params.
        '401':
          description: Failed due to unauthorized access.
        '403':
          description: This error occurred when there is some validation error or you don't have access to that resource.
        '404':
          description: Requested resource may not exist.
        '500':
          description: This is due to internal server error reason, in this case please contact our support team with attached uuid.
      tags:
      - JustCall AI
      security:
      - AccessToken: []
  /v2/calls_ai/manual_score/{id}:
    get:
      operationId: call_ai_manual_score
      summary: Get call manual score
      description: Average of all manual scores added.
      parameters:
      - name: id
        required: true
        in: path
        description: Unique id of the call generated by JustCall
        schema:
          type: number
      - name: platform
        required: false
        in: query
        description: Select the platform to retrieve associated call details.
        schema:
          default: justcall
          enum:
          - justcall
          - sales_dialer
          type: string
      responses:
        '200':
          description: Successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CallAIManualScoreResponseDTO'
        '400':
          description: Failed due to bad request params.
        '401':
          description: Failed due to unauthorized access.
        '403':
          description: This error occurred when there is some validation error or you don't have access to that resource.
        '404':
          description: Requested resource may not exist.
        '500':
          description: This is due to internal server error reason, in this case please contact our support team with attached uuid.
      tags:
      - JustCall AI
      security:
      - AccessToken: []
  /v2/meetings_ai:
    get:
      operationId: meeting_ai_list
      summary: List meetings AI data
      description: Utilize this endpoint to access AI generated analysis for all instances from all the meetings or filter instances based on a specific meeting Id(applicable for recurring meetings where there are multiple instances for each meeting Id).
      parameters:
      - name: platform
        required: false
        in: query
        description: Select the platform to retrieve associated meeting details.
        schema:
          enum:
          - zoom
          - google_meet
          type: string
      - name: meeting_id
        required: false
        in: query
        description: Filter meeting instances based on the Id of the meeting. This Id is unique for each meeting URL and can have multiple instances recorded under it for recurring events under the same URL.
        schema:
          type: string
      - description: Set fetch_transcription to true to fetch the transcription generated by JustCall AI for your meeting instances. Default entry is false. Please note that the list of speakers is only returned along with the transcription hence it will only appear when fetch_transcription is set to true.
        required: false
        name: fetch_transcription
        in: query
        schema:
          default: false
          type: boolean
      - description: Set fetch_summary to true to fetch the summary generated by JustCall AI for your meeting. Default entry is true.
        required: false
        name: fetch_summary
        in: query
        schema:
          default: true
          type: boolean
      - description: Set fetch_ai_insights to true to fetch the coaching insights generated by JustCall AI for your meeting. Default entry is true.
        required: false
        name: fetch_ai_insights
        in: query
        schema:
          default: true
          type: boolean
      - name: agent_id
        required: false
        in: query
        description: ID of the agent for whom the AI data for meetings are to be fetched. Agent ID can be accessed using <a href="https://justcall.io/developer-docs/#list_users">List all users API</a>.
        schema:
          type: number
      - name: from_datetime
        required: false
        in: query
        description: Datetime in <b>yyyy-mm-dd hh:mm:ss</b> or <b>yyyy-mm-dd</b> format starting from when the meetings AI data are to be fetched in <b>UTC Timezone</b>.
        schema:
          type: string
      - name: to_datetime
        required: false
        in: query
        description: Datetime in <b>yyyy-mm-dd hh:mm:ss</b> or <b>yyyy-mm-dd</b> format till when the meetings AI data are to be fetched in <b>UTC Timezone</b>.
        schema:
          type: string
      - name: page
        required: false
        in: query
        description: Page number for which meetings are to be fetched.
        schema:
          type: number
      - name: per_page
        required: false
        in: query
        description: Number count of meetings to be fetched per page.<br>Default value is 10 and maximum value is 20.
        schema:
          type: number
      - name: order
        required: false
        in: query
        description: 'Order in which the meetings should appear based on ‘Date created’ASC : Older data will appear first followed by recent oneDESC: Recent data will appear first followed by older one'
        schema:
          default: desc
          enum:
          - asc
          - desc
          - natural
          type: string
      responses:
        '200':
          description: Successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MeetingAIResponseDTO'
        '400':
          description: Failed due to bad request params.
        '401':
          description: Failed due to unauthorized access.
        '403':
          description: This error occurred when there is some validation error or you don't have access to that resource.
        '404':
          description: Requested resource may not exist.
        '500':
          description: This is due to internal server error reason, in this case please contact our support team with attached uuid.
      tags:
      - JustCall AI
      security:
      - AccessToken: []
  /v2.1/meetings_ai:
    get:
      operationId: meeting_ai_list_v21
      summary: List meetings AI data
      description: Utilize this endpoint to access AI generated analysis for all instances from all the meetings or filter instances based on a specific meeting Id(applicable for recurring meetings where there are multiple instances for each meeting Id).
      parameters:
      - name: platform
        required: false
        in: query
        description: Select the platform to retrieve associated meeting details.
        schema:
          enum:
          - zoom
          - google_meet
          type: string
      - name: meeting_id
        required: false
        in: query
        description: Filter meeting instances based on the Id of the meeting. This Id is unique for each meeting URL and can have multiple instances recorded under it for recurring events under the same URL.
        schema:
          type: string
      - description: Set fetch_transcription to true to fetch the transcription generated by JustCall AI for your meeting instances. Default entry is false. Please note that the list of speakers is only returned along with the transcription hence it will only appear when fetch_transcription is set to true.
        required: false
        name: fetch_transcription
        in: query
        schema:
          default: false
          type: boolean
      - description: Set fetch_summary to true to fetch the summary generated by JustCall AI for your meeting. Default entry is true.
        required: false
        name: fetch_summary
        in: query
        schema:
          default: true
          type: boolean
      - description: Set fetch_ai_insights to true to fetch the coaching insights generated by JustCall AI for your meeting. Default entry is true.
        required: false
        name: fetch_ai_insights
        in: query
        schema:
          default: true
          type: boolean
      - name: agent_id
        required: false
        in: query
        description: ID of the agent for whom the AI data for meetings are to be fetched. Agent ID can be accessed using <a href="https://justcall.io/developer-docs/#list_users">List all users API</a>.
        schema:
          type: number
      - name: from_datetime
        required: false
        in: query
        description: Datetime in <b>yyyy-mm-dd hh:mm:ss</b> or <b>yyyy-mm-dd</b> format starting from when the meetings AI data are to be fetched in <b>user's timezone</b>.
        schema:
          type: string
      - name: to_datetime
        required: false
        in: query
        description: Datetime in <b>yyyy-mm-dd hh:mm:ss</b> or <b>yyyy-mm-dd</b> format till when the meetings AI data are to be fetched in <b>user's timezone</b>.
        schema:
          type: string
      - name: page
        required: false
        in: query
        description: Page number for which meetings are to be fetched.
        schema:
          type: number
      - name: per_page
        required: false
        in: query
        description: Number count of meetings to be fetched per page.<br>Default value is 10 and maximum value is 20.
        schema:
          type: number
      - name: order
        required: false
        in: query
        description: 'Order in which the meetings should appear based on ‘Date created’ASC : Older data will appear first followed by recent oneDESC: Recent data will appear first followed by older one'
        schema:
          default: desc
          enum:
          - asc
          - desc
          - natural
          type: string
      - name: fetch_smart_chapters
        required: false
        in: query
        description: Set fetch_smart_chapters to true to fetch the smart chapters generated by JustCall AI for your meeting. Default entry is true.
        schema:
          default: true
          type: boolean
      responses:
        '200':
          description: Successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MeetingAIResponseDTOV21'
        '400':
          description: Failed due to bad request params.
        '401':
          description: Failed due to unauthorized access.
        '403':
          description: This error occurred when there is some validation error or you don't have access to that resource.
        '404':
          description: Requested resource may not exist.
        '500':
          description: This is due to internal server error reason, in this case please contact our support team with attached uuid.
      tags:
      - JustCall AI
      security:
      - AccessToken: []
  /v2/meetings_ai/{instance_sid}:
    get:
      operationId: meeting_ai_get
      summary: Get AI data
      description: Retrieve AI generated analysis for a particular instance of a meeting using this endpoint.
      parameters:
      - name: instance_sid
        required: true
        in: path
        description: Unique sid of the meeting instance generated by JustCall
        schema:
          type: string
      - description: Set fetch_transcription to true to fetch the transcription generated by JustCall AI for your meeting instances. Default entry is false. Please note that the list of speakers is only returned along with the transcription hence it will only appear when fetch_transcription is set to true.
        required: false
        name: fetch_transcription
        in: query
        schema:
          default: false
          type: boolean
      - description: Set fetch_summary to true to fetch the summary generated by JustCall AI for your meeting. Default entry is true.
        required: false
        name: fetch_summary
        in: query
        schema:
          default: true
          type: boolean
      - description: Set fetch_ai_insights to true to fetch the coaching insights generated by JustCall AI for your meeting. Default entry is true.
        required: false
        name: fetch_ai_insights
        in: query
        schema:
          default: true
          type: boolean
      responses:
        '200':
          description: Successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MeetingAIResponseDTO'
        '400':
          description: Failed due to bad request params.
        '401':
          description: Failed due to unauthorized access.
        '403':
          description: This error occurred when there is some validation error or you don't have access to that resource.
        '404':
          description: Requested resource may not exist.
        '500':
          description: This is due to internal server error reason, in this case please contact our support team with attached uuid.
      tags:
      - JustCall AI
      security:
      - AccessToken: []
  /v2.1/meetings_ai/{instance_sid}:
    get:
      operationId: meeting_ai_get_v21
      summary: Get AI data
      description: Retrieve AI generated analysis for a particular instance of a meeting using this endpoint.
      parameters:
      - name: instance_sid
        required: true
        in: path
        description: Unique sid of the meeting instance generated by JustCall
        schema:
          type: string
      - description: Set fetch_transcription to true to fetch the transcription generated by JustCall AI for your meeting instances. Default entry is false. Please note that the list of speakers is only returned along with the transcription hence it will only appear when fetch_transcription is set to true.
        required: false
        name: fetch_transcription
        in: query
        schema:
          default: false
          type: boolean
      - description: Set fetch_summary to true to fetch the summary generated by JustCall AI for your meeting. Default entry is true.
        required: false
        name: fetch_summary
        in: query
        schema:
          default: true
          type: boolean
      - description: Set fetch_ai_insights to true to fetch the coaching insights generated by JustCall AI for your meeting. Default entry is true.
        required: false
        name: fetch_ai_insights
        in: query
        schema:
          default: true
          type: boolean
      - name: fetch_smart_chapters
        required: false
        in: query
        description: Set fetch_smart_chapters to true to fetch the smart chapters generated by JustCall AI for your meeting. Default entry is true.
        schema:
          default: true
          type: boolean
      responses:
        '200':
          description: Successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MeetingAIResponseDTOV21'
        '400':
          description: Failed due to bad request params.
        '401':
          description: Failed due to unauthorized access.
        '403':
          description: This error occurred when there is some validation error or you don't have access to that resource.
        '404':
          description: Requested resource may not exist.
        '500':
          description: This is due to internal server error reason, in this case please contact our support team with attached uuid.
      tags:
      - JustCall AI
      security:
      - AccessToken: []
components:
  schemas:
    CallAIAnalyticsResponseDTO:
      type: object
      properties:
        id:
          type: number
          example: 123456
          description: Unique id of the call as generated by JustCall
        call_sid:
          type: string
          example: CA0247d967e9bb3c284163a37a43XXXX
          description: Unique call sid of the call as generated by JustCall
        platform:
          type: string
          default: justcall
          description: The platform associated with the call
          enum:
          - justcall
          - sales_dialer
        call_analytics:
          $ref: '#/components/schemas/CallAnalytics'
    SmartChapterDTO:
      type: object
      properties:
        section:
          type: string
          example: IVR Options and Call Forwarding
          description: The section title for the smart chapter.
        overview:
          example:
          - conversation: Introduction of IVR options for call forwarding.
          - conversation: Repeated prompts for reaching store manager, sales, support, and product.
          description: An array of overview items for the smart chapter.
          type: array
          items:
            $ref: '#/components/schemas/SmartChapterOverviewDTO'
    CallTranscriptionDTO:
      type: object
      properties:
        speaker_id:
          type: string
          example: 1
          description: speaker id
        speaker_name:
          type: string
          example: John Doe
          description: speaker name
        sentence:
          type: string
          example: Hey, Can I know the status with the deal?
          description: transcription sentence
        timestamp:
          example:
            starttime: 0
            endtime: 0
          description: Transcription timestamp
          allOf:
          - $ref: '#/components/schemas/TranscriptionTimeStampDTO'
    TranscriptionTimeStampDTO:
      type: object
      properties:
        starttime:
          type: number
          default: 0
        endtime:
          type: number
          default: 0
    CallAISummaryResponseDTO:
      type: object
      properties:
        id:
          type: number
          example: 123456
          description: Unique id of the call as generated by JustCall
        call_sid:
          type: string
          example: CA0247d967e9bb3c284163a37a43XXXX
          description: Unique call sid of the call as generated by JustCall
        platform:
          type: string
          default: justcall
          description: The platform associated with the call
          enum:
          - justcall
          - sales_dialer
        call_summary:
          type: string
          example: Call summary
          description: A summary of the key highlights and takeaways from a call
    CallAIMomentResponseDTO:
      type: object
      properties:
        id:
          type: number
          example: 123456
          description: Unique id of the call as generated by JustCall
        call_sid:
          type: string
          example: CA0247d967e9bb3c284163a37a43XXXX
          description: Unique call sid of the call as generated by JustCall
        platform:
          type: string
          default: justcall
          description: The platform associated with the call
          enum:
          - justcall
          - sales_dialer
        call_moments:
          example:
          - exams
          - math
          - confidence
          description: List of most important keywords associated with a call
          type: array
          items:
            type: string
    MeetingTranscriptionDTO:
      type: object
      properties:
        speaker_id:
          type: string
          example: aab59ae2-c795-48ea
          description: speaker id
        sentence:
          type: string
          example: Hey, Can I know the status with the deal?
          description: transcription sentence
        timestamp:
          example:
            starttime: 0
            endtime: 0
          description: Transcription timestamp
          allOf:
          - $ref: '#/components/schemas/TranscriptionTimeStampDTO'
    CallAISentimentResponseDTO:
      type: object
      properties:
        id:
          type: number
          example: 123456
          description: Unique id of the call as generated by JustCall
        call_sid:
          type: string
          example: CA0247d967e9bb3c284163a37a43XXXX
          description: Unique call sid of the call as generated by JustCall
        platform:
          type: string
          default: justcall
          description: The platform associated with the call
          enum:
          - justcall
          - sales_dialer
        customer_sentiment:
          type: string
          example: Positive
          description: Overall analysis of the sentiment of the customer based on words and tone
    MeetingAIResponseDTO:
      type: object
      properties:
        instance_sid:
          type: string
          example: CA0247d967e9bb3c284163a37a43XXXX
          description: Unique sid associated with a particular instance conducted under a meeting URL
        meeting_id:
          type: string
          example: meet-XXXX-XXXX
          description: Id of the meeting as generated by JustCall. This Id is unique for each meeting URL <br>and can have multiple instances recorded under it for recurring events under the same URL.
        meeting_title:
          type: string
          description: Title of the meeting
        platform:
          type: string
          description: Platform from among the following:<br>Google Meet<br>Zoom<br>
        instance_date:
          type: string
          description: Date of instance in UTC
          example: '2025-08-12'
        instance_time:
          type: string
          description: Time of instance in UTC
          example: '10:00:00'
        instance_user_date:
          type: string
          description: Date of instance in users timezone
          example: '2025-08-12'
        instance_user_time:
          type: string
          description: Time of instance in users timezone
          example: 07:30:00
        instance_duration:
          type: number
          description: Duration of the instance in seconds
          example: 1000
        instance_friendly_duration:
          type: string
          description: Duration of the instance in standard hh:mm:ss format
          example: 00:16:40
        instance_moments:
          example:
          - exams
          - math
          - confidence
          description: List of most important keywords associated with a call
          type: array
          items:
            type: string
        sentiment:
          type: string
          example: Positive
          description: Overall analysis of the sentiment of the customer based on words and tone
        tags:
          default: []
          example:
          - demo
          - follow-up
          description: Tags added by the user(agent) for a call
          type: array
          items:
            type: string
        manual_instance_score:
          type: number
          default: 0
          example: 4
          description: Average of all manual scores added
        speakers:
          description: List of all the participants of the meeting instance (Array of Objects). This field is only returned in the API response when fetch_transcription is set to true.
          default: []
          type: array
          items:
            $ref: '#/components/schemas/SpeakerDTO'
        instance_transcription:
          default: []
          example:
          - speaker_id: aab59ae2-c795-48ea
            sentence: Hey, Can I know the status with the deal?
            timestamp:
              starttime: 0
              endtime: 0
          description: A translation of the audio call into written text in a script like format
          type: array
          items:
            $ref: '#/components/schemas/MeetingTranscriptionDTO'
        instance_summary:
          type: string
          example: Meeting summary
          description: A summary of the key highlights and takeaways from a meeting
    CallAnalyticsInteractionStats:
      type: object
      properties:
        agent_speak_time:
          type: number
          default: 0
          description: agent_speak_time
        customer_speak_time:
          type: number
          default: 0
          description: customer_speak_time
        dead_air_time:
          type: number
          default: 0
          description: dead_air_time
        monologue_duration:
          type: number
          default: 0
          description: monologue_duration
        customer_story_duration:
          type: number
          default: 0
          description: customer_story_duration
        interactivity_count:
          type: number
          default: 0
          description: interactivity_count
    SmartChapterOverviewDTO:
      type: object
      properties:
        conversation:
          type: string
          example: Introduction of IVR options for call forwarding.
          description: A sentence or summary of a specific conversation point.
    CallAiResponseDTOV2:
      type: object
      properties:
        id:
          type: number
          example: 123456
          description: Unique id of the call as generated by JustCall
        call_sid:
          type: string
          example: CA0247d967e9bb3c284163a37a43XXXX
          description: Unique call sid of the call as generated by JustCall
        platform:
          type: string
          default: justcall
          description: The platform associated with the call
          enum:
          - justcall
          - sales_dialer
        call_moments:
          example:
          - exams
          - math
          - confidence
          description: List of most important keywords associated with a call
          type: array
          items:
            type: string
        customer_sentiment:
          type: string
          example: Positive
          description: Overall analysis of the sentiment of the customer based on words and tone
        overall_sentiment:
          type: string
          example: Positive
          description: Overall sentiment of the entire call based on Google NLP analysis
        call_score:
          type: number
          default: 0
          description: Overall score of the call out of 10
        call_score_parameters:
          $ref: '#/components/schemas/CallScoreParameter'
        tags:
          default: []
          example:
          - demo
          - follow-up
          description: Tags added by the user(agent) for a call
          type: array
          items:
            type: string
        manual_call_score:
          type: number
          default: 0
          example: 4
          description: Average of all manual scores added
        call_transcription:
          default: []
          example:
          - speaker_id: 1
            sentence: Hey, Can I know the status with the deal?
            timestamp:
              starttime: 0
              endtime: 0
          description: A translation of the audio call into written text in a script like format
          allOf:
          - $ref: '#/components/schemas/CallTranscriptionDTO'
        call_summary:
          type: string
          example: Call summary
          description: A summary of the key highlights and takeaways from a call
        call_analytics:
          $ref: '#/components/schemas/CallAnalytics'
    SpeakerDTO:
      type: object
      properties:
        id:
          type: string
          example: aab59ae2-c795-48ea
          description: speaker id
        name:
          type: string
          example: John Smith
          description: speaker name
    MeetingAIResponseDTOV21:
      type: object
      properties:
        instance_sid:
          type: string
          example: CA0247d967e9bb3c284163a37a43XXXX
          description: Unique sid associated with a particular instance conducted under a meeting URL
        meeting_id:
          type: string
          example: meet-XXXX-XXXX
          description: Id of the meeting as generated by JustCall. This Id is unique for each meeting URL <br>and can have multiple instances recorded under it for recurring events under the same URL.
        meeting_title:
          type: string
          description: Title of the meeting
        platform:
          type: string
          description: Platform from among the following:<br>Google Meet<br>Zoom<br>
        instance_date:
          type: string
          description: Date of instance in UTC
          example: '2025-08-12'
        instance_time:
          type: string
          description: Time of instance in UTC
          example: '10:00:00'
        instance_user_date:
          type: string
          description: Date of instance in users timezone
          example: '2025-08-12'
        instance_user_time:
          type: string
          description: Time of instance in users timezone
          example: 07:30:00
        instance_duration:
          type: number
          description: Duration of the instance in seconds
          example: 1000
        instance_friendly_duration:
          type: string
          description: Duration of the instance in standard hh:mm:ss format
          example: 00:16:40
        instance_moments:
          example:
          - exams
          - math
          - confidence
          description: List of most important keywords associated with a call
          type: array
          items:
            type: string
        sentiment:
          type: string
          example: Positive
          description: Overall analysis of the sentiment of the customer based on words and tone
        tags:
          default: []
          example:
          - demo
          - follow-up
          description: Tags added by the user(agent) for a call
          type: array
          items:
            type: string
        manual_instance_score:
          type: number
          default: 0
          example: 4
          description: Average of all manual scores added
        speakers:
          description: List of all the participants of the meeting instance (Array of Objects). This field is only returned in the API response when fetch_transcription is set to true.
          default: []
          type: array
          items:
            $ref: '#/components/schemas/SpeakerDTO'
        instance_transcription:
          default: []
          example:
          - speaker_id: aab59ae2-c795-48ea
            sentence: Hey, Can I know the status with the deal?
            timestamp:
              starttime: 0
              endtime: 0
          description: A translation of the audio call into written text in a script like format
          type: array
          items:
            $ref: '#/components/schemas/MeetingTranscriptionDTO'
        instance_summary:
          type: string
          example: Meeting summary
          description: A summary of the key highlights and takeaways from a meeting
        invitee_emails:
          description: List of emails of all invitees in the meeting.
          default: []
          example:
          - john.doe@example.com
          - jane.smith@abc.com
          type: array
          items:
            type: string
        smart_chapters:
          description: An array of chapters identified by AI (Array of Objects).
          default: []
          example:
          - section: Introduction and Purpose of Call
            overview:
            - conversation: John introduces himself and the purpose of the call.
            - conversation: James mentions he is looking for a multiline dialer for new team members
          type: array
          items:
            $ref: '#/components/schemas/SmartChapterDTO'
        interaction_stats:
          description: Interaction stats generated by JustCall AI for your meeting instances.
          default: {}
          example:
            agent_speak_time: 36.1
            customer_speak_time: 23.2
            dead_air_time: 40.7
            monologue_duration: 8.5
            customer_story_duration: 6
            interactivity_count: 85
          allOf:
          - $ref: '#/components/schemas/CallAnalyticsInteractionStats'
    CallScoreParameter:
      type: object
      properties:
        dead_air_time:
          type: number
          default: 0
          description: dead_air_time
        filler_word:
          type: number
          default: 0
          description: filler_word
        de_escalation:
          type: number
          default: 0
          description: de_escalation
        empathy:
          type: number
          default: 0
          description: empathy
        talk_listen_ratio:
          type: number
          default: 0
          description: talk_listen_ratio
        greetings:
          type: number
          default: 0
          description: greetings
        words_per_minute:
          type: number
          default: 0
          description: words_per_minute
        monologue_duration:
          type: number
          default: 0
          description: monologue_duration
        call_etiquette:
          type: number
          default: 0
          description: call_etiquette
        customer_sentiment_score:
          type: number
          default: 0
          description: customer_sentiment_score
    CallAIManualScoreResponseDTO:
      type: object
      properties:
        id:
          type: number
          example: 123456
          description: Unique id of the call as generated by JustCall
        call_sid:
          type: string
          example: CA0247d967e9bb3c284163a37a43XXXX
          description: Unique call sid of the call as generated by JustCall
        platform:
          type: string
          default: justcall
          description: The platform associated with the call
          enum:
          - justcall
          - sales_dialer
        manual_call_score:
          type: number
          default: 0
          example: 4
          description: Average of all manual scores added
    CallAiResponseDTOV21:
      type: object
      properties:
        id:
          type: number
          example: 123456
          description: Unique id of the call as generated by JustCall
        call_sid:
          type: string
          example: CA0247d967e9bb3c284163a37a43XXXX
          description: Unique call sid of the call as generated by JustCall
        platform:
          type: string
          default: justcall
          description: The platform associated with the call
          enum:
          - justcall
          - sales_dialer
        call_moments:
          example:
          - exams
          - math
          - confidence
          description: List of most important keywords associated with a call
          type: array
          items:
            type: string
        customer_sentiment:
          type: string
          example: Positive
          description: Overall analysis of the sentiment of the customer based on words and tone
        overall_sentiment:
          type: string
          example: Positive
          description: Overall sentiment of the entire call based on Google NLP analysis
        call_score:
          type: number
          default: 0
          description: Overall score of the call out of 10
        call_score_parameters:
          $ref: '#/components/schemas/CallScoreParameter'
        tags:
          default: []
          example:
          - demo
          - follow-up
          description: Tags added by the user(agent) for a call
          type: array
          items:
            type: string
        manual_call_score:
          type: number
          default: 0
          example: 4
          description: Average of all manual scores added
        call_transcription:
          default: []
          example:
          - speaker_id: 1
            sentence: Hey, Can I know the status with the deal?
            timestamp:
              starttime: 0
              endtime: 0
          description: A translation of the audio call into written text in a script like format
          allOf:
          - $ref: '#/components/schemas/CallTranscriptionDTO'
        call_summary:
          type: string
          example: Call summary
          description: A summary of the key highlights and takeaways from a call
        action_items:
          type: string
          example: Action Items
          description: A summary of the key action items from a call
        interaction_stats:
          $ref: '#/components/schemas/CallAnalyticsInteractionStats'
        smart_chapters:
          example:
          - section: IVR Options and Call Forwarding
            overview:
            - conversation: Introduction of IVR options for call forwarding.
            - conversation: Repeated prompts for reaching store manager, sales, support, and product.
          description: An array of smart chapters.
          type: array
          items:
            $ref: '#/components/schemas/SmartChapterDTO'
    CallAnalytics:
      type: object
      properties:
        interaction_stats:
          $ref: '#/components/schemas/CallAnalyticsInteractionStats'
  securitySchemes:
    AccessToken:
      type: apiKey
      in: header
      name: Authorization
      description: 'The API key can be put in the Authorization header. i.e Authorization: api_key:api_secret. If you use cURL, specify -u “api_key:api_secret”'
